Repository Pink-Crab/Perique_Plugin_Life_Cycle, pull requests merged in 2023-04, with the labels that each got.

#45 added event item filter
  README.md
  phpstan.neon.dist
  src/Plugin_Life_Cycle.php
  src/Plugin_State_Controller.php
  tests/Unit/Test_Plugin_State_Controller.php
Labels: enhancement

#51 Feature: reintroduce assume base file path
  src/Plugin_Life_Cycle.php
  src/Plugin_State_Controller.php
  tests/Integration/Test_Use_Plugin_State_Controller.php
  tests/Unit/Test_Module.php
Labels: enhancement

#52 update dev deps
  composer.json
Labels: dependencies

#53 Release/2.0.1
  README.md
  composer.json
  src/Plugin_Life_Cycle.php
  src/Plugin_State_Controller.php
  tests/Integration/Test_Use_Plugin_State_Controller.php
  tests/Unit/Test_Module.php
Labels: documentation, enhancement, dependencies

#54 Update readme
  README.md
Labels: documentation

#55 Correct error in readme
  README.md
Labels: documentation
